# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "/Users/mdundek/workspaces/perso/multipaas", "/home/vagrant/multipaas"
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
  config.vm.define "unipaas.cp.bionic" do |instance|
    instance.vm.box = "ubuntu/bionic64"
    instance.vm.hostname = "unipaas.cp.bionic"
    instance.vm.network "public_network", bridge: "en0: Wi-Fi (Wireless)", ip: "192.168.68.151"
    instance.vm.provider "virtualbox" do |v|
      v.name = "unipaas.cp.bionic"
      v.memory = 4092
    end
  end
end