apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tbd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tbd
    spec:
      containers:
      - name: tbd
        image: "tbt"